### ISSUE TITLE
[BUG]: A few problems with "int" datatype

### ISSUE THREAD

**Issue by coxipi** [michaelrizvi/deep-linear-rnn#1]
### Description of the bug

Hi! Just want to point out some problems I had when I tried to use "int" datatype. 

## **1.** Type issue when using "int" datatype. I had the error  

```
# RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float
# forward, ret = _VF.rnn_tanh_cell(
```
which comes from during the `rnn` evaluation
```python 
rnn(x if i == 0 else h_next[i-1], h[i])
```
I naively casted both `x` and `h` as float in `DeepRNN.forward`
```python 
    def forward(self, x, h):
        x = x.float() 
        h = [hi.float() for hi in h]
```
and the computation ended normally. 

### solution? 

Use `dtype=torch.float` to define x,y in the "int" case, so values are values are sampled in {0,1,2,...,vocab_size-1} with entries being floats

> [!WARNING]  
> **EDIT: This didn't  work ... the dumb casting above in the forward function did though**

```python
x = torch.randint(0, self.vocab_size, (self.n_samples, self.seq_len), dtype=torch.float)
```

On the other hand, if `h` must be casted as long (Maybe we don't want that, but for a simple copy task the hidden states will simply hold different x entries, so that might be sufficient ... I don't understand ML enough yet 🙃 ), we would need to add the datatype as an input
> [!WARNING]  
> **EDIT: Seeing the previous 'solution' didn't work, I should specify I have not tested this one yet**
```python
class DeepRNN(nn.Module):
     # datatype must be given
    def __init__(self, input_size, hidden_size, output_size, num_layers, activation='relu', readout_activation='identity', datatype="real"):
...
    def init_hidden(self, batch_size):
        return [torch.zeros(batch_size, self.hidden_size, dtype = torch.long if self.datatype == "int" else torch.float) for _ in range(self.num_layers)]
```

### my config

I used the following config. I think I've correctly changed the Task for a Tokenized one, where there any more changes that should have been made in the config?

```yaml
train_dataset:
  _target_: dataset.SyntheticCopyDataset
  n_samples: 1000
  seq_len: &seq_len
    10
  vocab_size: &vs
    2
  lookahead: &p 
    6
  datatype: &datatype
    "int"

val_dataset:
  _target_: dataset.SyntheticCopyDataset
  n_samples: 200
  seq_len: *seq_len
  vocab_size: *vs
  lookahead: *p
  datatype: *datatype

datamodule:
  _target_: dataset.SyntheticCopyDataModule
  batch_size: *vs
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}

trainer:
  max_epochs: 100
  enable_progress_bar: True
  log_every_n_steps: 10
  limit_train_batches: 0.1
  accelerator: "cpu"

model:
  _target_: model.DeepRNN
  input_size: ${train_dataset.vocab_size}
  output_size: ${train_dataset.vocab_size}
  hidden_size: &n
  # having hidden_size different than batch size causes an error
    2
  # L>= p/(k-1) = p/(n/d-1) = p(2-1) = p
  num_layers: &L 
    6 # minimum L that works with given n,p,d
  activation: 'relu'
  readout_activation: 'identity'

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 1000
    mode: min
    verbose: True

task :
  # _target_: task.CopyTaskRegression
  _target_: task.CopyTaskTokenized
  model: ${model}
  lr: 1e-3
```

## **2.** The need to set  the `batch_size` and `hidden_size` the same as `vocab_size`. 

I'm less sure of this, but if you test "int", you might see this too. I need to check more on this problem. 

* If I replace `batch_size` above with 256 instead of 2==vocab_size, I get an another error with `rnn`

```
torch/nn/modules/rnn.py", line 1583, in forward
    ret = _VF.rnn_tanh_cell(
RuntimeError: input has inconsistent input_size: got 200 expected 2
```

* If I replace `hidden_size` with 4, I get : 
```
torch/nn/modules/rnn.py", line 1583, in forward
    ret = _VF.rnn_tanh_cell(
RuntimeError: hidden0 has inconsistent hidden_size: got 2, expected 4
```

### Steps To Reproduce

1. see
2. above
3. sorry
4. for that

### Additional Information

see above
